#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_MIGRATION_USER" $POSTGRES_BACKEND_DB <<-EOSQL
    GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public to $POSTGRES_BACKEND_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to $POSTGRES_BACKEND_USER;
EOSQL