apiVersion: v1
kind: Service
metadata:
  namespace: queue-system
  name: backend-service
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
spec:
  selector:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: backend
  type: NodePort
  ports:
    - name: backend-port
      protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: backend-port