FROM golang:1.17.1-alpine AS base
WORKDIR /app
COPY ./backend ./backend
COPY ./main.go ./main.go
COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum

FROM base AS builder
RUN go build -o main /app/main.go

FROM alpine:3.14
EXPOSE 8000
WORKDIR /app
COPY --from=builder /app/main /app
RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup && \
    mkdir /app/logs && \
    chown appuser:appgroup -R /app
USER appuser
ENTRYPOINT /app/main