FROM golang:1.17.1-alpine AS base
WORKDIR /app
COPY ./proto ./proto
COPY ./grpc ./grpc

# FROM base AS builder
# RUN go build -o main /app/grpc/main.go

# FROM alpine:3.14
# EXPOSE 8000
# WORKDIR /app
# COPY --from=builder /app/main /app
# RUN addgroup -g 1001 appgroup && \
#     adduser -u 1000 -S appuser -g 1001 -G appgroup && \
#     mkdir /app/logs && \
#     chown appuser:appgroup -R /app
# ENTRYPOINT /app/main