version: "3.5"

services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    env_file: 
      - .env
    environment:
        - TZ=Asia/Taipei
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
          max-file: "3"
  db:
      image: postgres:13
      restart: always
      env_file: 
        - .env
      environment:
        - POSTGRES_INITDB_ARGS=--data-checksums
      volumes:
          - db_data:/var/lib/postgresql/data

volumes: 
  db_data: {}