// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jerry0420/queue-system/backend/domain"
	mock "github.com/stretchr/testify/mock"
)

// CustomerUseCaseInterface is an autogenerated mock type for the CustomerUseCaseInterface type
type CustomerUseCaseInterface struct {
	mock.Mock
}

// UpdateCustomer provides a mock function with given fields: ctx, oldStatus, newStatus, customer
func (_m *CustomerUseCaseInterface) UpdateCustomer(ctx context.Context, oldStatus string, newStatus string, customer *domain.Customer) error {
	ret := _m.Called(ctx, oldStatus, newStatus, customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *domain.Customer) error); ok {
		r0 = rf(ctx, oldStatus, newStatus, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
