apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: queue-system-ingress
  namespace: queue-system
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    # cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Access-Control-Allow-Origin https://queue.com;
      add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
      add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Connection,Content-Type,Authorization';
      add_header Access-Control-Allow-Credentials true

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;

      send_timeout 75s;
      keepalive_timeout 75s 75s;
      keepalive_requests 10000;

      gzip_vary on;
      gzip_proxied any;
      gzip_buffers 16 8k;

      etag on;
      
      add_header Cache-Control "no-cache";

      if ($request_uri ~* \.(css|gif|jpe?g|png|svg|ico)) {
        add_header Cache-Control "max-age=31536000";
      }

      if ($request_uri ~* \.(js)) {
        add_header Cache-Control "private, max-age=31536000";
      }

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - queue.com
    secretName: queue-system-secret
  rules:
  - host: queue.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/aws/deploy.yaml