apiVersion: v1
kind: Service
metadata:
  namespace: queue-system
  name: frontend-service
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
spec:
  selector:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend
  # type: NodePort
  type: LoadBalancer
  ports:
    - name: frontend-port
      protocol: TCP
      # nodePort: 30001
      port: 80
      targetPort: 3000