DROP TABLE IF EXISTS customers;

DROP TABLE IF EXISTS queues;

DROP TABLE IF EXISTS stores;

DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TYPE IF EXISTS store_status;

DROP TYPE IF EXISTS customer_status;