apiVersion: v1 
kind: Pod 
metadata: 
  namespace: queue-system
  name: alpine
spec: 
  containers: 
  - name: alpine 
    image: alpine:3.14
    resources:
          requests:
            memory: "32Mi"
            cpu: "0.1"
          limits:
            memory: "64Mi"
            cpu: "0.2"
    command: ["/bin/sh","-c"]
    args: 
      - wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.6/grpc_health_probe-linux-amd64;
        chmod +x /bin/grpc_health_probe;
        apk add curl;
        sleep 10000;
    imagePullPolicy: IfNotPresent 
    volumeMounts:
      - name: ca-crt
        mountPath: "/run/secrets/ca-crt"
  volumes:
    - name: ca-crt
      secret:
        secretName: ca-crt
        items:
        - key: CA-CRT
          path: .ca-crt
          mode: 0444