apiVersion: v1
kind: Service
metadata:
  namespace: queue-system
  name: grpc-service
  labels:
    app: grpc
    app.kubernetes.io/name: grpc
    app.kubernetes.io/instance: grpc
spec:
  selector:
    app: grpc
    app.kubernetes.io/name: grpc
    app.kubernetes.io/instance: grpc
  clusterIP: None
  ports:
    - name: grpc-port
      protocol: TCP
      port: 80
      targetPort: 8002