version: "3.7"

services: 
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile.frontend
      target: base
    container_name: frontend
    networks:
      - queue_system
    stdin_open: true
    tty: true
    env_file: 
      - .env.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../:/app

  grpc:
    build:
      context: ../
      dockerfile: Dockerfile.grpc
      target: base
    container_name: grpc
    networks:
      - queue_system
    stdin_open: true
    tty: true
    env_file: 
      - .env.grpc
    ports:
      - "8002:8002"
    volumes:
      - ../:/app
      - ./secret_grpc:/run/secrets/grpc-secret/grpc-secret
      - ../grpc/logs/:/app/grpc/logs/

  backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend
      target: base
    container_name: backend
    networks:
      - queue_system
    stdin_open: true
    tty: true
    env_file: 
      - .env
    ports:
      - "8000:8000"
      - "3001:3001"
    volumes:
      - ../:/app
      - ./secret:/run/secrets/backend-secret/backend-secret
      - ../backend/logs/:/app/backend/logs/

  db_admin:
    image: dpage/pgadmin4:5
    ports:
      - '8001:80'
    networks:
      - queue_system
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeerywa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=jerry0315
    volumes:
      - ../db_admin/servers.json:/pgadmin4/servers.json

networks: 
  queue_system:
    external: true