version: "3.5"

services: 
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile
      target: builder-frontend
    container_name: frontend
    networks:
      - queue_system
    command: >
      sh -c "npm run build && 
      tail -f /dev/null"
    stop_signal: SIGINT # set sotp signal from sigterm to sigint, because this container is running by "command", which won't receive sigterm to stop theemself.
    stop_grace_period: 1s
    env_file: 
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../build:/app/build

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
      target: builder
    container_name: backend
    networks:
      - queue_system
    depends_on:
      - frontend
    stdin_open: true
    tty: true
    env_file: 
      - ../.env
    ports:
      - "8000:8000"
      - "3001:3001"
    volumes:
      - ../:/app
      - ../logs:/app/logs

  db_admin:
    image: dpage/pgadmin4:5
    ports:
      - '8001:80'
    networks:
      - queue_system
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeerywa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=jerry0315
    volumes:
      - ../db_admin/servers.json:/pgadmin4/servers.json