version: "3.7"

services: 
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile.frontend
    restart: always
    container_name: frontend
    networks:
      - queue_system
    env_file: 
      - .env.frontend
    user: 1000:1001
    ports:
      - "80:3000"
    volumes:
      - frontend_log_dir:/var/log/nginx:rw
    logging:
      driver: "none"

  backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend
    restart: always
    container_name: backend
    networks:
      - queue_system
    env_file: 
      - .env
    user: 1000:1001
    secrets:
      - source: backend-secret
        target: /run/secrets/backend-secret/backend-secret
        uid: '1000'
        gid: '1001'
        mode: 0440
    ports:
      - "8000:8000"
    volumes:
      - backend_log_dir:/app/logs:rw
    logging:
      driver: "none"

volumes: 
  backend_log_dir: {}
  frontend_log_dir: {}

networks: 
  queue_system:
    external: true

secrets:
  backend-secret:
    file: ./secret