version: "3.5"

services: 
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    networks:
      - queue_system
    env_file: 
      - .env
    ports:
      - "8000:8000"
    volumes:
      - log_dir:/app/logs:rw
    logging:
      driver: "none"

volumes: 
  log_dir: {}

networks: 
  queue_system:
    external: true