version: "3.7"

services: 
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile.frontend
      target: base
    container_name: frontend
    networks:
      - queue_system
    stdin_open: true
    tty: true
    env_file: 
      - .env.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../build:/app/build

  backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend
      target: base
    container_name: backend
    networks:
      - queue_system
    stdin_open: true
    tty: true
    env_file: 
      - .env
    ports:
      - "8000:8000"
      - "3001:3001"
    volumes:
      - ../:/app
      - ./secret:/run/secrets/backend-secret/backend-secret
      - ../logs:/app/logs

  db_admin:
    image: dpage/pgadmin4:5
    ports:
      - '8001:80'
    networks:
      - queue_system
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeerywa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=jerry0315
    volumes:
      - ../db_admin/servers.json:/pgadmin4/servers.json

networks: 
  queue_system:
    external: true