version: "3.7"

services: 
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile.frontend
      target: base
    container_name: frontend
    networks:
      - queue_system
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - ../envs/.env.frontend:/etc/config/.env.frontend

  grpc:
    build:
      context: ../
      dockerfile: Dockerfile.grpc
      target: base
    container_name: grpc
    networks:
      - queue_system
    stdin_open: true
    tty: true
    ports:
      - "8002:8002"
    volumes:
      - ../:/app
      - ../envs/.secret_grpc:/run/secrets/grpc-secret/.grpc-secret
      - ../cert/server.crt:/run/secrets/server-crt/.server-crt
      - ../cert/server.key:/run/secrets/server-key/.server-key
      - ../cert/ca.crt:/run/secrets/ca-crt/.ca-crt
      - ../envs/.env.grpc:/etc/config/.env.grpc
      - ../grpc/logs/:/app/grpc/logs/

  backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend
      target: base
    container_name: backend
    networks:
      - queue_system
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
      - "3001:3001"
    volumes:
      - ../:/app
      - ../envs/.secret:/run/secrets/backend-secret/.backend-secret
      - ../cert/ca.crt:/run/secrets/ca-crt/.ca-crt
      - ../envs/.env:/etc/config/.env
      - ../backend/logs/:/app/backend/logs/

  nginx:
    image: nginx:1.18-alpine
    ports:
    - '80:80'
    env_file: 
      - ../envs/.env.nginx
    container_name: nginx
    command: >
      sh -c "/nginx.conf.dev.sh
      && nginx -g 'daemon off;' -c /nginx.conf"
    volumes:
        - ../scripts/nginx/nginx.conf.dev.sh:/nginx.conf.sh
    networks:
      - queue_system

networks: 
  queue_system:
    external: true