#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_BACKEND_USER WITH PASSWORD '$POSTGRES_BACKEND_PASSWORD';    
    CREATE DATABASE $POSTGRES_BACKEND_DB;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES TO $POSTGRES_BACKEND_USER;
EOSQL