#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_BACKEND_USER WITH PASSWORD '$POSTGRES_BACKEND_PASSWORD';
    CREATE DATABASE $POSTGRES_BACKEND_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_BACKEND_DB TO $POSTGRES_BACKEND_USER;
EOSQL